component GCovLine inherits Rectangle{
  in property <int> line-num;
  in property <string> line-contents;


  HorizontalLayout {
    spacing: 2px;
    alignment: stretch;

    Rectangle {
      background: lightgray;
      width: 12mm;
      Text {text: line-num; color: black; font-size: 13pt;}
    }
    Rectangle {
      background: dimgray;

      HorizontalLayout {
        padding: 4px;
        Text {text: line-contents; font-size: 13pt;}
      }
    }
  }
}

export component App inherits Window {
  preferred-width: 800px;
  preferred-height: 600px;
  title: @tr("GCOV Viewer");
  background: #353535f8;

  VerticalLayout {
    width: 100%;
    alignment: start;

    GCovLine {line-num: 0; line-contents: "hello";}
  }
}